<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Octopus Scene</title>
        <link type="text/css" href="/css/ui-lightness/jquery-ui-1.8.7.custom.css" rel="stylesheet" />
        <?php echo $this->headLink(); ?>
        
        <script type="text/javascript" src="/js/jquery-1.4.4.min.js"></script>
        <script type="text/javascript" src="/js/jquery-ui-1.8.7.custom.min.js"></script>
        <?php echo $this->headScript(); ?>

    </head>
    <body>
        <div id="wrapper">
        <?php echo $this->layout()->content; ?>
        </div>
    </body>
</html>